IMAGE_NAME = "generic/rhel8"

ANSIBLE_NODES = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..ANSIBLE_NODES).each do |i|
        config.vm.define "remote-node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 20}", virtualbox__intnet: "intnet"
            node.vm.hostname = "remote-node-#{i}"

            # naming the virtualmachine
            node.vm.provider :virtualbox do |vb|
                vb.name = "remote-node-#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end
            
            # execute nodes-sshd.sh for configuring ssh.
            node.vm.provision :shell, path: "files/nodes-sshd.sh"
            node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "host_ssh_public_key"
            node.vm.provision "shell", inline: <<-SHELL
                cat host_ssh_public_key >> /home/vagrant/.ssh/authorized_keys
            SHELL
            #node.vm.provision "ansible" do |ansible|
            #    ansible.compatibility_mode = "2.0"
            #    ansible.playbook = "ansible-node-config.yml"
            #    ansible.extra_vars = {
            #        node_ip: "192.168.50.#{i + 20}",
            #    }
            #end
        end
    end
        
end