#IMAGE_NAME = "bento/ubuntu-16.04"
IMAGE_NAME = "bento/ubuntu-20.04"
NODES = 2
CLUSTER_NAME = "demo"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    #config.vm.provider "virtualbox" do |v|
    #    v.memory = 1024
    #    v.cpus = 2
    #end
      
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        # customize virtualmachine
        master.vm.provider :virtualbox do |vb|
            vb.name = "#{CLUSTER_NAME}-k8s-master"
            vb.memory = 2048
            vb.cpus = 2
        end

        config.vm.network "forwarded_port",
        guest: 8001,
        host:  8001,
        auto_correct: true
        
        config.vm.network "forwarded_port",
        guest: 30000,
        host:  30000,
        auto_correct: true
        
        config.vm.network "forwarded_port",
        guest: 8443,
        host:  8443,
        auto_correct: true

        master.vm.provision "ansible_local" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end

    (1..NODES).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            # customize virtualmachine
            node.vm.provider :virtualbox do |vb|
                vb.name = "node-#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end
            node.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
            end
        end
    end
end
