IMAGE_NAME = "generic/rhel8"
VM_NAME = "AnsibleController"
VM_AAP_HUB_NAME = "AutomationHub"
NODES = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..NODES).each do |i|
        config.vm.define "#{VM_NAME}-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            #node.vm.network "private_network", ip: "192.168.50.#{i + 20}", virtualbox__intnet: "intnet"
            node.vm.hostname = "#{VM_NAME}-#{i}"

            # VM customization
            node.vm.provider :virtualbox do |vb|
                vb.name = "#{VM_NAME}-#{i}"
                vb.memory = 4096
                vb.cpus = 2
            end
        end
    end

    (1..NODES).each do |i|
        config.vm.define "#{VM_AAP_HUB_NAME}-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            #node.vm.network "private_network", ip: "192.168.50.#{i + 20}", virtualbox__intnet: "intnet"
            node.vm.hostname = "#{VM_AAP_HUB_NAME}-#{i}"

            # VM customization
            node.vm.provider :virtualbox do |vb|
                vb.name = "#{VM_AAP_HUB_NAME}-#{i}"
                vb.memory = 4096
                vb.cpus = 2
            end
        end
    end
        
end